### ISSUE TITLE
The addition of pseudo masks makes MIOU decrease？

### ISSUE THREAD

**Issue by calibacy** [sahilkhose/FloodNet#3]
Excuse me, I've been reproducing your paper. but the addition of pseudo masks makes MIOU decrease. I wonder  if you have any solution? thanks a lot!
PS: I reduced the image size to 256*256, and the ratio of unlabeled images to labeled images is only 2:1.

**Comment by sahilkhose** [comment]
Can you try training at the settings mentioned in the notebook?

**Comment by calibacy** [comment]
> 

yes I tried, but seems the pseudo labels deviate too much from the ground truth.

**Comment by sahilkhose** [comment]
Can you provide an image of the pseudo label, and point to why you think they are deviating from the ground truth?

**Comment by calibacy** [comment]
> Can you provide an image of the pseudo label, and point to why you think they are deviating from the ground truth?

After a few epochs, there is only background in the pseudo label, and MIOU falls into zero.

**Comment by sahilkhose** [comment]
Our segmentation did not benefit significantly from the pseudo labels as much as the classification, although the results did improve. You can see the predictions [here](https://share.streamlit.io/sahilkhose/floodnet/main/stream_app.py)

**Comment by calibacy** [comment]
> Our segmentation did not benefit significantly from the pseudo labels as much as the classification, although the results did improve. You can see the predictions [here](https://share.streamlit.io/sahilkhose/floodnet/main/stream_app.py)

well I get it, but I couldn't repeat the same results as yours when I run the code :( A little sad

**Comment by sahilkhose** [comment]
When I re-visit the dataset I will make the notebooks re-producible and provide the model weights. 
If you want to discuss the problem statement, you can send me an email at sahilkhose18@gmail.com
